language: cpp
dist: xenial
compiler:
  - gcc
  - clang 

addons: 
  apt: 
    packages: 
      - libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

script: 
  - qmake
  - make debug # Error by the original author
  - ./cpp_benchmark_array_versus_std_vector
  - make release
  - ./cpp_benchmark_array_versus_std_vector
