language: cpp
dist: bionic
compiler:
  - gcc
  - clang 

addons: 
  apt: 
    packages: 
      - libboost-all-dev

install: 
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

script: 
  - qmake
  - make --silent debug # Intentional error to show one should profile in release mode
  - ./cpp_benchmark_array_versus_std_vector
  - make --silent release
  - ./cpp_benchmark_array_versus_std_vector
