language: cpp
dist: bionic
compiler:
  - gcc
  - clang 

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default

script: 
  - qmake
  - make --silent debug # Intentional error to show one should profile in release mode
  - ./cpp_benchmark_array_versus_std_vector
  - make --silent release
  - ./cpp_benchmark_array_versus_std_vector
